// <auto-generated />
namespace Online_Food_Corner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddWorker : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddWorker));
        
        string IMigrationMetadata.Id
        {
            get { return "201904291057457_AddWorker"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
