//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Food_Corner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int admin_id { get; set; }
        public string email { get; set; }
        public string admin_password { get; set; }
        public int product_id { get; set; }
        public int order_id { get; set; }
        public int delivery_id { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
