//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Food_Corner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int worker_id { get; set; }
        public string worker_name { get; set; }
        public int salary { get; set; }
        public string worker_status { get; set; }
        public int order_id { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
